name = "IntensityScans"
uuid = "6cf45cad-7870-4d4d-b567-e05cd8632aa3"
authors = ["Esti Gajda", "Morten F. Rasmussen <10264458+mofii@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
